import express from 'express';
import {createUser, getAllUsers} from '../controller/userController.js';
import cors from 'cors';
import { generateJWT, verifyJWT } from '../middlewares/userMiddleware.js';
import dotenv from 'dotenv';
dotenv.config();
const router = express();
router.use(cors());
const userRouter = express.Router();
userRouter.post('/users', generateJWT, createUser);
userRouter.get('/users', verifyJWT, getAllUsers);
export default userRouter;